quarkus:
  datasource:
    db-kind: mysql
    username: xkyii
    password: xk0(8&6
    jdbc:
      url: mysql://i.xkyii.cn:3306/yfty_platform

xkyss:
  codegen:
    source:
      platform:
        name: platform
        kind: db
    target:
      repository:
        name: repository
        template: repository
#    generate:
#      - source: platform
#        target: repository